name = "investment-api"
main = "index.py"
compatibility_date = "2026-02-19"
compatibility_flags = ["python_workers"]

# Account info
account_id = "f823a3f5752d5b771fddf73ea67c3056"

[env.production]
name = "investment-api"
