name = "investment-aramac"
compatibility_date = "2026-02-19"
compatibility_flags = ["nodejs_compat"]

# For Cloudflare Pages
pages_build_output_dir = "dist"

[env.production]
name = "investment-aramac"
